### ISSUE TITLE
ErrorMsg 乱码

### ISSUE THREAD

**Issue by zhangyiser** [openctp/openctp-tts-python#2]
响应失败, ErrorID=75, ErrorMsg=CTP:솬탸뗇슼쪧냜듎쫽뎬쿞ꎬ뗇슼놻뷻횹

**Comment by Jedore** [comment]
@zhangyiser 可以多提供一些信息，以方便复现修复。

**Comment by zhangyiser** [comment]
> @zhangyiser 可以多提供一些信息，以方便复现修复。

Python 3.10.13
openctp-tts-6.6.9.0

"""
    交易demo - 连接并登录交易服务
"""
import time

from openctp_tts import tdapi


def limit_order():
    """限价单
    注意选择一个相对活跃的合约及合适的价格
    """
    req = tdapi.CThostFtdcInputOrderField()
    req.BrokerID = broker_id
    req.InvestorID = user
    req.ExchangeID = 'CZCE'
    req.InstrumentID = 'AP310'  # 合约ID
    req.LimitPrice = 100  # 价格
    req.OrderPriceType = tdapi.THOST_FTDC_OPT_LimitPrice  # 价格类型限价单
    req.Direction = tdapi.THOST_FTDC_D_Buy  # 买
    req.CombOffsetFlag = tdapi.THOST_FTDC_OF_Open  # 开仓
    req.CombHedgeFlag = tdapi.THOST_FTDC_HF_Speculation
    req.VolumeTotalOriginal = 1
    req.IsAutoSuspend = 0
    req.IsSwapOrder = 0
    req.TimeCondition = tdapi.THOST_FTDC_TC_GFD
    req.VolumeCondition = tdapi.THOST_FTDC_VC_AV
    req.ContingentCondition = tdapi.THOST_FTDC_CC_Immediately
    req.ForceCloseReason = tdapi.THOST_FTDC_FCC_NotForceClose
    return req


class CTdSpiImpl(tdapi.CThostFtdcTraderSpi):
    """ 交易回调实现类 """

    def __init__(self, _api: tdapi.CThostFtdcTraderApi):
        super().__init__()
        self._api = _api

    def OnFrontConnected(self):
        """ 前置连接成功 """
        print("交易前置连接成功")

        # 认证请求
        req = tdapi.CThostFtdcReqAuthenticateField()
        req.BrokerID = broker_id
        req.UserID = user
        req.AppID = appid
        req.AuthCode = authcode
        self._api.ReqAuthenticate(req, 0)

    def OnFrontDisconnected(self, nReason: int):
        """ 前置断开 """
        print("交易前置连接断开: nReason=", nReason)

    def OnRspAuthenticate(self, pRspAuthenticateField: tdapi.CThostFtdcRspAuthenticateField,
                          pRspInfo: tdapi.CThostFtdcRspInfoField, nRequestID: int, bIsLast: bool):
        """ 客户端认证应答 """
        if pRspInfo and pRspInfo.ErrorID:
            print("认证失败: ErrorID=", pRspInfo.ErrorID, "ErrorMsg=", pRspInfo.ErrorMsg)
            return

        print("认证成功")

        if pRspInfo is None or pRspInfo.ErrorID == 0:
            # 登录请求
            req = tdapi.CThostFtdcReqUserLoginField()
            req.BrokerID = broker_id
            req.UserID = user
            req.Password = password
            req.UserProductInfo = "openctp"
            self._api.ReqUserLogin(req, 0)

    def OnRspUserLogin(self, pRspUserLogin: tdapi.CThostFtdcRspUserLoginField,
                       pRspInfo: tdapi.CThostFtdcRspInfoField, nRequestID: int, bIsLast: bool):
        """ 登录应答 """
        if pRspInfo and pRspInfo.ErrorID:
            print("登录失败: ErrorID=", pRspInfo.ErrorID, "ErrorMsg=", pRspInfo.ErrorMsg)
            return

        print("登录成功:", pRspUserLogin.UserID, "TradingDay=", pRspUserLogin.TradingDay)

    def OnRspOrderInsert(self, pInputOrder: tdapi.CThostFtdcInputOrderField,
                         pRspInfo: tdapi.CThostFtdcRspInfoField, nRequestID: int, bIsLast: bool):
        """ 报单录入响应 """
        if pRspInfo and pRspInfo.ErrorID:
            print("报单录入失败: ErrorID=", pRspInfo.ErrorID, "ErrorMsg=", pRspInfo.ErrorMsg)
            return

        print("报单录入成功")

    def OnRtnOrder(self, pOrder: tdapi.CThostFtdcOrderField):
        """ 报单回报 """
        print("报单回报:",
              "InstrumentID:", pOrder.InstrumentID,
              "ExchangeID:", pOrder.ExchangeID,
              "FrontID:", pOrder.FrontID,
              "SessionID:", pOrder.SessionID,
              "OrderRef:", pOrder.OrderRef,
              "OrderSysID:", pOrder.OrderSysID,
              "OrderPriceType:", pOrder.OrderPriceType,
              "Direction:", pOrder.Direction,
              "CombOffsetFlag:", pOrder.CombOffsetFlag,
              "LimitPrice:", pOrder.LimitPrice,
              "VolumeTotalOriginal:", pOrder.VolumeTotalOriginal,
              "OrderStatus:", pOrder.OrderStatus,
              "InsertDate:", pOrder.InsertDate,
              "InsertTime:", pOrder.InsertTime,
              )

    def OnErrRtnOrderInsert(self, pInputOrder: tdapi.CThostFtdcInputOrderField,
                            pRspInfo: tdapi.CThostFtdcRspInfoField):
        """报单录入错误回报"""
        if pRspInfo and pRspInfo.ErrorID:
            print("报单录入错误回报: ErrorID=", pRspInfo.ErrorID, "ErrorMsg=", pRspInfo.ErrorMsg)

    def open_position(self, order: tdapi.CThostFtdcInputOrderField, request_id: int):
        """持有头寸
        - 录入错误时对应响应OnRspOrderInsert、OnErrRtnOrderInsert，
        - 正确时对应回报OnRtnOrder、OnRtnTrade。
        """
        print("> 开仓")
        self._api.ReqOrderInsert(order, request_id)


if __name__ == '__main__':
    # 实例化交易请求类
    td_front = 'tcp://121.37.80.177:20002'
    user = ''
    password = ''
    authcode = '0000000000000000'
    appid = 'test'
    broker_id = '9999'
    api = tdapi.CThostFtdcTraderApi.CreateFtdcTraderApi(user)  # type: tdapi.CThostFtdcTraderApi
    print("TTS交易API版本号:", api.GetApiVersion())
    print("交易前置:", td_front)
    # 实例化交易回调实现类
    spi = CTdSpiImpl(api)
    # 注册交易前置地址
    api.RegisterFront(td_front)
    # 交易请求实例 注册 交易回调实例
    api.RegisterSpi(spi)
    # 订阅私有流
    api.SubscribePrivateTopic(tdapi.THOST_TERT_QUICK)
    # 订阅公有流
    api.SubscribePublicTopic(tdapi.THOST_TERT_QUICK)
    # 初始化交易实例
    api.Init()

    time.sleep(3)
    order = limit_order()
    spi.open_position(order, 0)

    # 阻塞 等待
    print("Press Enter key to exit ...")
    input()

    # 释放实例
    api.Release()

**Comment by Jedore** [comment]
@zhangyiser 什么系统，是 Mac 吗？

**Comment by zhangyiser** [comment]
> @zhangyiser 什么系统，是 Mac 吗？

是的

**Comment by Jedore** [comment]
> > @zhangyiser 什么系统，是 Mac 吗？
> 
> 是的

好的，我看看，这几天应该就能修复。

**Comment by Jedore** [comment]
@zhangyiser Mac编码问题修复了，安装最新版试一下。
